"""For holding keys, tokens, webhooks, and private names"""
SLACK_WEBHOOK_URL = '<YOUR SLACK WEBHOOK URL>'
DEFAULT_SLACK_USER = '<YOUR DEFAULT USERNAME TO SEND MESSAGES AS>'
DEFAULT_SLACK_ROOM = '<DEFAULT CHANNEL TO SEND MESSAGE TO>'
DEBUG_SLACK_ROOM = '<DEFAULT CHANNEL TO SEND MESSAGE TO FOR DEV/DEBUG PURPOSES>'